<a href="https://colab.research.google.com/github/MFBS2005/gomycode/blob/main/checkpoint9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import mlxtend
from mlxtend.preprocessing import TransactionEncoder
dataset = [['Skirt', 'Sneakers', 'Scarf', 'Pants', 'Hat'],
        ['Sunglasses', 'Skirt', 'Sneakers', 'Pants', 'Hat'],
        ['Dress', 'Sandals', 'Scarf', 'Pants', 'Heels'],
        ['Dress', 'Necklace', 'Earrings', 'Scarf', 'Hat', 'Heels', 'Hat'],
      ['Earrings', 'Skirt', 'Skirt', 'Scarf', 'Shirt', 'Pants']]
te=TransactionEncoder()
te_ary=te.fit(dataset).transform(dataset)   
xx=pd.DataFrame(te_ary, columns=te.columns_)
xx.head()

   Dress  Earrings    Hat  Heels  ...  Shirt  Skirt  Sneakers  Sunglasses
0  False     False   True  False  ...  False   True      True       False
1  False     False   True  False  ...  False   True      True        True
2   True     False  False   True  ...  False  False     False       False
3   True      True   True   True  ...  False  False     False       False
4  False      True  False  False  ...   True   True     False       False

[5 rows x 12 columns]

In [ ]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(xx, min_support=0.6, use_colnames=True) #Instead of column indices we can use column names.
frequent_itemsets

   support        itemsets
0      0.6           (Hat)
1      0.8         (Pants)
2      0.8         (Scarf)
3      0.6         (Skirt)
4      0.6  (Pants, Scarf)
5      0.6  (Pants, Skirt)

In [ ]:
from mlxtend.frequent_patterns import association_rules 
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.7)

  antecedents consequents  antecedent support  ...    lift  leverage  conviction
0     (Pants)     (Scarf)                 0.8  ...  0.9375     -0.04         0.8
1     (Scarf)     (Pants)                 0.8  ...  0.9375     -0.04         0.8
2     (Pants)     (Skirt)                 0.8  ...  1.2500      0.12         1.6
3     (Skirt)     (Pants)                 0.6  ...  1.2500      0.12         inf

[4 rows x 9 columns]

In [ ]:
association_rules(frequent_itemsets,metric="lift",min_threshold=1)

  antecedents consequents  antecedent support  ...  lift  leverage  conviction
0     (Pants)     (Skirt)                 0.8  ...  1.25      0.12         1.6
1     (Skirt)     (Pants)                 0.6  ...  1.25      0.12         inf

[2 rows x 9 columns]

In [ ]:
#the skirt and the pants should be sold together with a lower price.
#the pants and the scarf should be sold separately.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import csv
x=pd.read_csv("/content/drive/My Drive/Market_Basket_Optimisation.csv",header=None)
x.info()
x

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

                 0                  1   ...       18         19
0            shrimp            almonds  ...  spinach  olive oil
1           burgers          meatballs  ...      NaN        NaN
2           chutney                NaN  ...      NaN        NaN
3            turkey            avocado  ...      NaN        NaN
4     mineral water               milk  ...      NaN        NaN
...             ...                ...  ...      ...        ...
7496         butter         light mayo  ...      NaN        NaN
7497        burgers  frozen vegetables  ...      NaN        NaN
7498        chicken                NaN  ...      NaN        NaN
7499       escalope          green tea  ...      NaN        NaN
7500           eggs    frozen smoothie  ...      NaN        NaN

[7501 rows x 20 columns]

In [ ]:
l1=[]
l2=[]
for i in range(1,x.shape[0]):
  ss=x.iloc[i]
  for j in ss:
    if type(j)==str:
      l1.append(j)
  l2.append(l1)
  l1=[]
l2

In [49]:
te=TransactionEncoder()
te_ary=te.fit(l2).transform(l2)   
rr=pd.DataFrame(te_ary, columns=te.columns_)
rr.head()

    asparagus  almonds  antioxydant juice  ...   yams  yogurt cake  zucchini
0       False    False              False  ...  False        False     False
1       False    False              False  ...  False        False     False
2       False    False              False  ...  False        False     False
3       False    False              False  ...  False        False     False
4       False    False              False  ...  False        False     False

[5 rows x 120 columns]

In [57]:
from mlxtend.frequent_patterns import apriori
frequent_itemsets=apriori(rr, min_support=0.03, use_colnames=True) 
frequent_itemsets

     support                            itemsets
0   0.033200                           (avocado)
1   0.033733                          (brownies)
2   0.087200                           (burgers)
3   0.030133                            (butter)
4   0.081067                              (cake)
5   0.046800                         (champagne)
6   0.060000                           (chicken)
7   0.163867                         (chocolate)
8   0.080400                           (cookies)
9   0.051067                       (cooking oil)
10  0.031733                    (cottage cheese)
11  0.179733                              (eggs)
12  0.079333                          (escalope)
13  0.170933                      (french fries)
14  0.043067                       (fresh bread)
15  0.063200                   (frozen smoothie)
16  0.095333                 (frozen vegetables)
17  0.052400                     (grated cheese)
18  0.132000                         (green tea)
19  0.098267                       (ground beef)
20  0.049467                     (herb & pepper)
21  0.047333                             (honey)
22  0.032400                          (hot dogs)
23  0.076400                    (low fat yogurt)
24  0.129600                              (milk)
25  0.238267                     (mineral water)
26  0.065733                         (olive oil)
27  0.095067                          (pancakes)
28  0.042400                            (salmon)
29  0.071333                            (shrimp)
30  0.050533                              (soup)
31  0.174133                         (spaghetti)
32  0.030267                      (tomato juice)
33  0.068400                          (tomatoes)
34  0.062533                            (turkey)
35  0.058533                  (whole wheat rice)
36  0.033200                   (eggs, chocolate)
37  0.034400           (chocolate, french fries)
38  0.032133                   (milk, chocolate)
39  0.052667          (mineral water, chocolate)
40  0.039200              (spaghetti, chocolate)
41  0.036400                (eggs, french fries)
42  0.030800                        (milk, eggs)
43  0.050933               (eggs, mineral water)
44  0.036533                   (spaghetti, eggs)
45  0.033733       (mineral water, french fries)
46  0.035733  (frozen vegetables, mineral water)
47  0.030933          (green tea, mineral water)
48  0.040933        (ground beef, mineral water)
49  0.039200            (spaghetti, ground beef)
50  0.048000               (milk, mineral water)
51  0.035467                   (spaghetti, milk)
52  0.033733           (mineral water, pancakes)
53  0.059733          (spaghetti, mineral water)

In [ ]:
association_rules(frequent_itemsets,metric="confidence",min_threshold=0.01)

In [59]:
association_rules(frequent_itemsets,metric="lift",min_threshold=1)

            antecedents          consequents  ...  leverage  conviction
0                (eggs)          (chocolate)  ...  0.003748    1.025576
1           (chocolate)               (eggs)  ...  0.003748    1.028681
2           (chocolate)       (french fries)  ...  0.006390    1.049354
3        (french fries)          (chocolate)  ...  0.006390    1.046800
4                (milk)          (chocolate)  ...  0.010896    1.111794
5           (chocolate)               (milk)  ...  0.010896    1.082714
6       (mineral water)          (chocolate)  ...  0.013623    1.073398
7           (chocolate)      (mineral water)  ...  0.013623    1.122506
8           (spaghetti)          (chocolate)  ...  0.010665    1.079042
9           (chocolate)          (spaghetti)  ...  0.010665    1.085551
10               (eggs)       (french fries)  ...  0.005678    1.039611
11       (french fries)               (eggs)  ...  0.005678    1.042202
12               (milk)               (eggs)  ...  0.007507    1.075977
13               (eggs)               (milk)  ...  0.007507    1.050402
14               (eggs)      (mineral water)  ...  0.008109    1.062957
15      (mineral water)               (eggs)  ...  0.008109    1.043286
16          (spaghetti)               (eggs)  ...  0.005236    1.038051
17               (eggs)          (spaghetti)  ...  0.005236    1.036563
18  (frozen vegetables)      (mineral water)  ...  0.013019    1.218433
19      (mineral water)  (frozen vegetables)  ...  0.013019    1.064279
20        (ground beef)      (mineral water)  ...  0.017520    1.305576
21      (mineral water)        (ground beef)  ...  0.017520    1.088782
22          (spaghetti)        (ground beef)  ...  0.022088    1.163699
23        (ground beef)          (spaghetti)  ...  0.022088    1.373959
24               (milk)      (mineral water)  ...  0.017121    1.209812
25      (mineral water)               (milk)  ...  0.017121    1.089982
26          (spaghetti)               (milk)  ...  0.012899    1.093022
27               (milk)          (spaghetti)  ...  0.012899    1.137029
28      (mineral water)           (pancakes)  ...  0.011082    1.054182
29           (pancakes)      (mineral water)  ...  0.011082    1.180687
30          (spaghetti)      (mineral water)  ...  0.018243    1.159468
31      (mineral water)          (spaghetti)  ...  0.018243    1.102184

[32 rows x 9 columns]